# This is a basic workflow to help you get started with Actions

name: Actualizar release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      release:
        description: 'The version to archive on Internet Archive'
        required: false
        default: 'latest'
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Paso que instala las dependencias necesarias para ejecutar el script de Python que se usará más adelante.
      - name: "Install dependencies"
        run: pip install -r scripts/archiver/requirements.txt
        
      #para manejar el evento de release. Este script probablemente se encarga de subir el release a Internet Archive.
      - name: "Handle release event"
        run: python3 scripts/archiver/ia_update_release.py
        env:
          IA_S3_ACCESS_KEY: ${{ secrets.IA_S3_ACCESS_KEY }}
          IA_S3_SECRET_KEY: ${{ secrets.IA_S3_SECRET_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
